In [7]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 41.7 ms
Wall time: 1.54 s


4.1 Numpy ndarray：多维数组对象

In [9]:
import numpy as np

In [16]:
data = np.random.randn(10,10,10)
data

array([[[ 2.09934452e-01, -2.90340014e-01, -1.42677593e+00,
         -8.36593812e-01,  2.19547992e-02, -1.32818755e+00,
          2.20052637e-01,  1.86725263e+00, -8.58682485e-01,
         -1.00719008e+00],
        [-8.79645123e-01,  1.46969087e+00, -1.28118614e-01,
         -1.01390258e+00,  1.72772710e+00, -1.58811095e+00,
         -1.16221516e-01, -7.24256906e-02, -7.47436068e-01,
          1.10113817e+00],
        [-2.17609008e-01, -4.82498853e-01,  5.87829313e-01,
          4.24033081e-01, -1.22117563e+00, -9.75692924e-01,
          2.43193095e-01, -2.44167873e+00,  4.01243325e-01,
          1.42580913e+00],
        [-4.30973816e-01,  8.09296569e-01, -4.13749780e-01,
         -4.00125243e-01, -9.18959276e-02,  6.92761735e-01,
          1.26420642e+00,  4.78119009e-02,  6.69823985e-01,
         -2.91140790e+00],
        [-5.70045520e-02, -1.11308769e-01,  1.67998492e+00,
         -1.13552795e+00, -1.02574817e+00, -1.07770295e+00,
          5.32927887e-01, -1.69601281e+00, -1.050420

上面创建一个正态分布随机数组（均值为0，方差为1）。下面对其进行了验算。

In [17]:
mean = np.mean(data)
variance = np.std(data) ** 2
print(mean, variance)

0.035441484703432335 0.9955040234627514


如何生成指定均值和方差的随机数组呢？下面的方差市sigma的平方。

sigma * np.matlib.randn(....) + mu

In [20]:
import numpy.matlib

random3 = 2.5 * np.matlib.randn((1000,1000)) + 3
mean3 = np.mean(random3)
variance3 = np.std(random3) ** 2
print(mean3, variance3)

3.000511277321299 6.240686421727078


回归正题

In [21]:
data = np.random.randn(2,3)
data

array([[ 0.04848065, -1.27262223, -0.28258323],
       [-0.6934856 , -1.66466967,  0.83721918]])

In [22]:
data * 10

array([[  0.48480651, -12.72622228,  -2.82583229],
       [ -6.93485597, -16.64669666,   8.37219183]])

In [23]:
data + data

array([[ 0.0969613 , -2.54524446, -0.56516646],
       [-1.38697119, -3.32933933,  1.67443837]])

In [24]:
data

array([[ 0.04848065, -1.27262223, -0.28258323],
       [-0.6934856 , -1.66466967,  0.83721918]])

ndarray的shape属性：数组维度， dtype属性：数组的数据类型

In [26]:
data.shape

(2, 3)

In [28]:
data.dtype

dtype('float64')

In [ ]:
4.1.1 生成ndarry

array函数接收任意的序列类型对象（也包括其他的数组）。

In [30]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [31]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
arr2.ndim

2

In [33]:
arr2.shape

(2, 4)

In [ ]:
除非显示的指定，否则np.array会自动的生成数组的数据类型

In [34]:
arr1.dtype

dtype('float64')

In [35]:
arr2.dtype

dtype('int32')

In [ ]:
除了np.array，还有很多其他函数可以创建新数组。例如zeros, ones等

In [36]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros(10)[0]

0.0

In [38]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [40]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
arange是Python内建函数range的数组版：

In [41]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
4.1.2 ndarray的数据类型

In [ ]:
dtype是一个特殊的对象，它包含了ndarray需要为某一类型数据所申明的内存信息：

In [42]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr1.dtype      

dtype('float64')

In [43]:
arr2 = np.array([1,2,3])
arr2.dtype

dtype('int32')

In [44]:
arr2 = np.array([1,2,3], dtype=np.int64)
arr2.dtype

dtype('int64')

In [ ]:
可以使用astype方法显示的转化数组的数据类型

In [45]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [46]:
float_arr = arr.astype(np.float)
float_arr.dtype

dtype('float64')

In [ ]:
上面都是整数转为浮点数。如果把浮点数转为整数，则小数点后的部分将被消除：

In [47]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [52]:
arr.astype(np.int)

array([ 3, -1, -2,  0, 12, 10])

In [54]:
arr.astype(np.int).dtype

dtype('int32')

In [ ]:
字符串数据转为浮点数例子：

In [56]:
numeric_strings = np.array(['1.25','-9.6','42'], dtype=np.string_)
numeric_strings.dtype

dtype('S4')

In [57]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [ ]:
可以用另一数组的dtype属性来定义新数组

In [59]:
int_array = np.arange(10)
calibers = np.array([0.22,0.27,.357,.380,.44,.50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
可以使用类型代码传入数据类型

In [60]:
empty_uint32 = np.empty(8,dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [ ]:
4.1.3 Numpy数组计算

In [66]:
arr = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [67]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [68]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [70]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [72]:
arr2 = np.array([[0,4,1],[7,2,12]], dtype=np.float64)
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [74]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [73]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [ ]:
4.1.4 基础索引与切片

In [75]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr[5]

5

In [77]:
arr[5:8]

array([5, 6, 7])

In [89]:
arr[5:8] = 15
arr

array([ 0,  1,  2,  3,  4, 15, 15, 15,  8,  9])

In [91]:
arr_slice = arr[5:8]
arr_slice

array([15, 15, 15])

In [93]:
arr_slice[1] = 33333
arr

array([    0,     1,     2,     3,     4,    15, 33333,    15,     8,
           9])

In [94]:
arr_slice[:] = 66
arr

array([ 0,  1,  2,  3,  4, 66, 66, 66,  8,  9])

In [ ]:
如果想要一份数组切片的拷贝可以像这样：arr[5:8].copy()

In [ ]:
更高维度的数组可以有更多的选择，二维数组如下

In [96]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
arr2d[2]

array([7, 8, 9])

In [98]:
arr2d[0,2]

3

In [ ]:
三维数组的例子

In [99]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [100]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
arr3d[0,0]

array([1, 2, 3])

In [103]:
old_value = arr3d[0].copy()
old_value

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [105]:
arr3d[0] = old_value
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
4.1.4.1 数组的切片索引

In [106]:
arr

array([ 0,  1,  2,  3,  4, 66, 66, 66,  8,  9])

In [107]:
arr[1:6]

array([ 1,  2,  3,  4, 66])

In [108]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [112]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [114]:
arr2d[:,-1:]

array([[3],
       [6],
       [9]])

In [115]:
arr2d[:2,1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [ ]:
4.1.5 布尔索引